[project]
name = "comfyui-reference-loader"
description = "Interactive image and video visual crop, video and audio with timeline trimming, reference loading nodes for ComfyUI"
version = "1.1.0"
readme = "README.md"
license = { file = "LICENSE" }
authors = [
    { name = "sthao42" },
]
dependencies = [
    "torch",
    "numpy",
    "pillow",
    "av",
]

[project.urls]
Repository = "https://github.com/sthao42/Comfyui-reference-loader"

[tool.comfy]
PublisherId = "sthao42"
DisplayName = "ComfyUI Reference Loader"
Icon = ""
