[project]
name = "comfyui-reference-loader"
version = "1.1.5"
description = "Interactive visual crop, timeline, audio, and reference loading nodes for ComfyUI"
readme = "README.md"
license = { text = "GPL-3.0" }
authors = [
    { name = "sthao42"}
]
dependencies = [
    "torch",
    "numpy",
    "pillow",
    "av",
]

[project.urls]
Homepage = "https://github.com/sthao42/Comfyui-reference-loader"
Repository = "https://github.com/sthao42/Comfyui-reference-loader"
"Bug Tracker" = "https://github.com/sthao42/Comfyui-reference-loader/issues"

[tool.comfy]
PublisherId = "sthao42"
DisplayName = "ComfyUI Reference Loader"
Icon = ""
